// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nudge.Learning.Data;

#nullable disable

namespace Nudge.Learning.Data.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    partial class LearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nudge.Learning.Decks.Models.Deck", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deck");

                    b.ToTable("deck", "learning");
                });

            modelBuilder.Entity("Nudge.Learning.Decks.Models.Deck", b =>
                {
                    b.OwnsOne("Nudge.Learning.Decks.ValueObjects.DeckDescription", "Description", b1 =>
                        {
                            b1.Property<long>("DeckId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(4096)
                                .HasColumnType("character varying(4096)")
                                .HasColumnName("description");

                            b1.HasKey("DeckId")
                                .HasName("pk_deck");

                            b1.ToTable("deck", "learning");

                            b1.WithOwner()
                                .HasForeignKey("DeckId")
                                .HasConstraintName("fk_deck_deck_id");
                        });

                    b.OwnsOne("Nudge.Learning.Decks.ValueObjects.DeckTitle", "Title", b1 =>
                        {
                            b1.Property<long>("DeckId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("title");

                            b1.HasKey("DeckId")
                                .HasName("pk_deck");

                            b1.ToTable("deck", "learning");

                            b1.WithOwner()
                                .HasForeignKey("DeckId")
                                .HasConstraintName("fk_deck_deck_id");
                        });

                    b.Navigation("Description");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
